### ISSUE TITLE
hosting suggestion

### ISSUE THREAD

**Issue by seiyria** [genshindev/api#20]
hey! I can't find a link to your discord server, but I wanted to suggest how to host this: since you only have static data, why not host it all on netlify? you don't really need a server component since you don't seem to do any logic, so maybe a static host is best.

**Comment by NurMarvin** [comment]
Hi! The Discord server is linked on the website as well in the repository (you need to click on the Discord "badge" in the README file). Regarding the hosting, I don't really have an issue hosting it on my own server, however I will check out how good of a solution Netlify would be, but it will take some time.

**Comment by nickmccurdy** [comment]
Netlify has GitHub sync. If you're only hosting static files then all you need to do is log into Netlify, select the repository, and set a build command (if necessary).

**Comment by NurMarvin** [comment]
Hi, I've looked into Netlify now and would have considered using it, but I've been made aware of another small service called @railwayapp by a friend of mine. Railway is a small startup hence I've decided to use it instead of Netlify because I feel like giving the "new kids in the block" a try. Maybe if I'm not happy with Railway I'll switch to Netlify, but for now I'll use Railway as mentioned.

**Comment by nickmccurdy** [comment]
Oh I didn't realize the API was dynamic, nevermind.
